service: overpass

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "sts:GetCallerIdentity"
       Resource:
         - "*"
    -  Effect: "Allow"
       Action:
         - "eks:DescribeCluster"
       Resource:
         - "*"
  timeout: 45
  vpc:
    securityGroupIds:
      - sg-72d81c0a
    subnetIds:
      - subnet-6f63c636
      - subnet-7902820e
      - subnet-1bed767e
  environment:
    CLUSTER_NAME: eyeem-eks-cluster-stage
functions:
  deploy:
    handler: handler.handler

plugins:
  - serverless-python-requirements

package:
  individually: true

custom:
  pythonRequirements:
    usePipenv: true
